main: powermate.VolumeControl
---
Build.build(project);
Build.oneJAR(project);
shell("jsmoothcmd.bat " + project.path("build/PowerMate.jsmooth"));
shell("ResHacker.exe -delete build/PowerMate.exe, build/PowerMate.exe, ICONGROUP, A, 1033");
shell("ResHacker.exe -delete build/PowerMate.exe, build/PowerMate.exe, ICONGROUP, A2, 1033");
shell("ResHacker.exe -add build/PowerMate.exe, build/PowerMate.exe, build/icon.ico, ICONGROUP, MAINICON, 0");
